name: dfc_gpt
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics: ^5.4.0
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints

flutter: null
