name: dfc_gpt
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  path: ^1.8.3
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.6
  dart_code_metrics:
    git: https://github.com/paulkastel/dart-code-metrics
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  json_serializable: ^6.7.1

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: LinuxPlugin
      macos:
        pluginClass: DfcGptPlugin
      windows:
        dartPluginClass: WindowsPlugin
