name: dfc_gpt
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter: null
