name: dfc_gpt
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ^3.6.0

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  path: ^1.9.1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  build_runner: ^2.4.15
  dart_code_metrics:
    git: https://github.com/rei-codes/dart-code-metrics
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  json_serializable: ^6.9.4

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: LinuxPlugin
      macos:
        pluginClass: DfcGptPlugin
      windows:
        dartPluginClass: WindowsPlugin
