name: dart_tools
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  intl: ^0.19.0
  path: ^1.9.0
  xml: ^6.5.0
  yaml_edit: ^2.2.1

dev_dependencies:
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics:
    git: https://github.com/paulkastel/dart-code-metrics
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
