name: dart_tools
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  intl: ^0.20.2
  path: ^1.9.1
  xml: ^6.5.0
  yaml_edit: ^2.2.2

dev_dependencies:
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics:
    git: https://github.com/JonasWanke/dart-code-metrics
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
